#ifndef __MMU_H__
#define __MMU_H__

#define TCR_CONFIG_REGION_48bit (((64 - 48) << 0) | ((64 - 48) << 16))
#define TCR_CONFIG_4KB ((0b00 << 14) |  (0b10 << 30))
#define TCR_CONFIG_DEFAULT (TCR_CONFIG_REGION_48bit | TCR_CONFIG_4KB)

#define MAIR_DEVICE_nGnRnE 0b00000000
#define MAIR_NORMAL_NOCACHE 0b01000100
#define MAIR_IDX_DEVICE_nGnRnE 0
#define MAIR_IDX_NORMAL_NOCACHE 1

#define PD_TABLE 0b11
#define PD_PAGE  0b11
#define PD_BLOCK 0b01
#define PD_ACCESS (1 << 10)
#define PD_ACCESS_PERMISSION	(1 << 6)
#define PD_READONLY     (1 << 7)
#define PD_NON_EXEC_EL0 (1UL << 54)

#define BOOT_PGD_ATTR PD_TABLE
#define BOOT_PUD_ATTR (PD_ACCESS | (MAIR_IDX_DEVICE_nGnRnE << 2) | PD_BLOCK)

#define LV3_PGD_ATTR PD_TABLE
#define LV3_PUD_ATTR PD_TABLE
#define LV3_PMD_ATTR (PD_ACCESS | (MAIR_IDX_DEVICE_nGnRnE << 2) | PD_BLOCK)
#define LV3_PMD_DEV_ATTR (PD_ACCESS | (MAIR_IDX_DEVICE_nGnRnE << 2) | PD_BLOCK)
#define LV3_PMD_NOR_ATTR (PD_ACCESS | (MAIR_IDX_NORMAL_NOCACHE << 2) | PD_BLOCK)

#define LV4_PGD_ATTR PD_TABLE
#define LV4_PUD_ATTR PD_TABLE
#define LV4_PMD_ATTR PD_TABLE
#define LV4_PTD_ATTR (PD_ACCESS | (MAIR_IDX_DEVICE_nGnRnE << 2) | PD_PAGE)

#define MMU_PTE_FLAGS	\
  (PD_PAGE | (MAIR_IDX_NORMAL_NOCACHE << 2) | PD_ACCESS | PD_ACCESS_PERMISSION)

#endif
