#ifndef MM_H
#define MM_H

#define TCR_CONFIG_REGION_48bit (((64 - 48) << 0) | ((64 - 48) << 16))
#define TCR_CONFIG_4KB ((0b00 << 14) |  (0b10 << 30))
#define TCR_CONFIG_DEFAULT (TCR_CONFIG_REGION_48bit | TCR_CONFIG_4KB)

#define MAIR_DEVICE_nGnRnE 0b00000000
#define MAIR_NORMAL_NOCACHE 0b01000100
#define MAIR_IDX_DEVICE_nGnRnE 0
#define MAIR_IDX_NORMAL_NOCACHE 1

#define PD_TABLE 0b11
#define PD_BLOCK 0b01
#define PD_ACCESS (1 << 10)
#define BOOT_PGD_ATTR PD_TABLE
#define BOOT_PUD_DEVICE_ATTR (PD_ACCESS | (MAIR_IDX_DEVICE_nGnRnE << 2) | PD_BLOCK)
#define BOOT_PUD_ATTR (PD_ACCESS | (MAIR_IDX_DEVICE_nGnRnE << 2) | PD_BLOCK)

#define PAGE_SIZE 8

#define PUD_AMOUNT 2
#define PUD_SIZE (PAGE_SIZE * PUD_AMOUNT)
#define PUD_BLOCK_SIZE (512 * PAGE_SIZE)

#define PMD_AMOUNT (1 * 512)
#define PMD_SIZE (PAGE_SIZE * PMD_AMOUNT)
#define PMD_BLOCK_SIZE (512 * PAGE_SIZE)

#define PTE_AMOUNT (1 * 512 * 512)
#define PTE_SIZE (PAGE_SIZE* PTE_AMOUNT)
#define PTE_BLOCK_SIZE (512 * PAGE_SIZE)

#endif
