#define CORE_TIMER 0
#define GET_FREQ 1
#define GET_CURRENT_COUNT 2
#define LOCAL_TIMER 3
#define CORE_TIMER_IGNORE 4
#define SYS_TIMER 5
#define RESET 6
#define CANCEL_RESET 7
#define SHOW_EXEC 8
#define SCHED_NEXT 9
#define GET_CURRENT_EL 10
#define DO_FORK 11
#define GET_RUNNING_TASK 12
#define EXEC 13
#define GET_CURRENT_TASK 14
#define EXIT 15
#define READ 16
#define WRITE 17