#ifndef __MMU_SIZE_H__
#define __MMU_SIZE_H__

#define TCR_CONFIG_REGION_48bit (((64 - 48) << 0) | ((64 - 48) << 16))
#define TCR_CONFIG_4KB ((0b00 << 14) |  (0b10 << 30))
#define TCR_CONFIG_DEFAULT (TCR_CONFIG_REGION_48bit | TCR_CONFIG_4KB)

#define MAIR_DEVICE_nGnRnE 0b00000000
#define MAIR_NORMAL_NOCACHE 0b01000100
#define MAIR_IDX_DEVICE_nGnRnE 0
#define MAIR_IDX_NORMAL_NOCACHE 1
#define MAIR_DEFAULT ( (MAIR_DEVICE_nGnRnE << (MAIR_IDX_DEVICE_nGnRnE * 8)) | (MAIR_NORMAL_NOCACHE << (MAIR_IDX_NORMAL_NOCACHE * 8)) )

#define PD_TABLE 0b11
#define PD_BLOCK 0b01
#define PD_ACCESS (1 << 10)
#define BOOT_PGD_ATTR PD_TABLE
#define BOOT_PUD_ATTR PD_TABLE
#define BOOT_PMD_ATTR_DEVICE (PD_ACCESS | (MAIR_IDX_DEVICE_nGnRnE << 2) | PD_BLOCK)
#define BOOT_PMD_ATTR_NORMAL (PD_ACCESS | (MAIR_IDX_NORMAL_NOCACHE << 2) | PD_BLOCK)
#define USER_PMD_ATTR PD_TABLE
#define USER_PTE_ATTR (PD_ACCESS | (MAIR_IDX_NORMAL_NOCACHE << 2) | PD_BLOCK)

#define SCTLR_MMU_DISABLE 	(0 << 0)
#define SCTLR_MMU_ENABLE 	(1 << 0)

#define KERNEL_FRAME_SHIFT 	21
#define KERNEL_FRAME_SIZE 	(1 << KERNEL_FRAME_SHIFT)

#define PAGE_TABLE_SHIFT 	(3+9)
#define PAGE_TABLE_SIZE 	(1 << PAGE_TABLE_SHIFT)

#define DEVICE_FRAME_NUM 	8
#define NORMAL_FRAME_NUM 	504

#define USER_FRAME_SHIFT 	12
#define USER_FRAME_SIZE 	(1 << USER_FRAME_SHIFT)

#define MEM_1G_SHIFT 		30
#define FRAME_NUM 			(1 << (MEM_1G_SHIFT - USER_FRAME_SHIFT))

#define USER_SPACE_START_ID	( 1 << (KERNEL_FRAME_SHIFT - USER_FRAME_SHIFT))
#define USER_SPACE_END_ID 	( FRAME_NUM - (1 << (KERNEL_FRAME_SHIFT - USER_FRAME_SHIFT + 3)) )





#endif